
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false

server:
  port: 9002

oauth:
  clientId: 9fbd4ae2-2db3-44c7-9544-88e80255b56e
  clientSecret: test
  checkTokenEndpointUrl: http://localhost:8080/oauth/check_token

---

spring:
  profiles: production
  datasource:
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/civil0-servant-register?user=root&password=secret&useSSL=false}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
