
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
  resources:
    add-mappings: false
  flyway:
    locations: classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 9002

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com.zaxxer.hikari: ERROR
    org.apache.http: WARN

oauth:
  clientId: ${CLIENT_ID:9fbd4ae2-2db3-44c7-9544-88e80255b56e}
  clientSecret: ${CLIENT_SECRET:test}
  serviceUrl: ${OAUTH_SERVICE_URL:http://localhost:8080}
  checkTokenEndpointUrl: "${oauth.serviceUrl}/oauth/check_token"
  tokenUrl: "${oauth.serviceUrl}/oauth/token"

identity:
  identityAPIUrl: "${oauth.serviceUrl}/api/identities"

govNotify:
  enabled: ${GOV_NOTIFY_ENABLED:false}
  key: ${GOV_NOTIFY_API_KEY:changeme}
  template:
    lineManager: ${GOV_NOTIFY_LINEMANAGER_TEMPLATE_ID:changeme}

---

spring:
  profiles: test, production
  datasource:
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/civil_servant_register?user=root&password=password&useSSL=false}
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true

govNotify:
  enabled: ${GOV_NOTIFY_ENABLED:true}