database:
  host: ${DATABASE_HOST:jdbc:mysql://localhost:3306}
  name: ${DATABASE_NAME:csrs}
  use-ssl: ${DATABASE_USESSL:false}
spring:
  datasource:
    url: ${DATASOURCE_URL:${database.host}/${database.name}?useSSL=${database.use-ssl}&requireSSL=false}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:my-secret-pw}
    platform: mysql
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  rest:
      detection-strategy: annotated
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  resources:
    add-mappings: false
  flyway:
    locations: classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: uk.gov.cshr.civilservant.config.CustomMySqlDialect
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: true
      path: "/h2-console"

server:
  port: 9002

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com.zaxxer.hikari: INFO

oauth:
  clientId: ${CLIENT_ID:9fbd4ae2-2db3-44c7-9544-88e80255b56e}
  clientSecret: ${CLIENT_SECRET:test}
  serviceUrl: ${OAUTH_SERVICE_URL:http://localhost:8080}
  checkTokenEndpoint: ${OAUTH_CHECK_TOKEN_ENDPOINT:/oauth/check_token}
  checkTokenEndpointUrl: "${oauth.serviceUrl}${oauth.checkTokenEndpoint}"
  tokenEndpoint: ${OAUTH_TOKEN_ENDPOINT:/oauth/token}
  tokenUrl: "${oauth.serviceUrl}${oauth.tokenEndpoint}"
  maxTotalConnections: 200
  defaultMaxConnectionsPerRoute: 100
  maxPerServiceUrl: 100
  jwtKey: ${jwt_key:key}

identity:
  identityAPIUrl: "${oauth.serviceUrl}/api/identities"
  agencyTokenUrl: "${oauth.serviceUrl}/agency/{agencyTokenUid}"
  identityAgencyTokenUrl: "${oauth.serviceUrl}/api/identity/agency/"

govNotify:
  enabled: ${GOV_NOTIFY_ENABLED:true}
  key: ${GOV_NOTIFY_API_KEY:changeme}
  template:
    lineManager: ${GOV_NOTIFY_LINEMANAGER_TEMPLATE_ID:changeme}

data-retention-windows:
  skills: ${DATA_RETENTION_WINDOW_SKILLS_DAYS:1095}

#Validation properties
agencyToken:
  capacity:
    max: ${AGENCY_TOKEN_MAX_CAPACITY:1500}
    min: ${AGENCY_TOKEN_MIN_CAPACITY:1}

domains:
  validation:
    regex: ${DOMAIN_VALIDATION_REGEX:^([\w-]+\.)+[\w-]{2,6}$}

