ALTER TABLE `quiz` CHANGE `created_on` `created_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `quiz` CHANGE `updated_on` `updated_on` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `shedlock` CHANGE `lock_until` `lock_until` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `shedlock` CHANGE `locked_at` `locked_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
